Add IaC scripts
wso2/iac-aws-wso2-products pull request #1
Opened 2023-11-30 04:44 UTC by PasanT9

## Purpose
> Deploy a AKS Cluster
> Additionally, there's an option to enable supplementary elements like MySQL, filestore, and secrets based on your requirements.

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2024-01-04 06:15 UTC, ThilinaManamgoda requested changes

2024-01-04 06:15 UTC, ThilinaManamgoda commented on sample_input.tfvars
> +]
Let's add a new line

2024-01-04 06:15 UTC, ThilinaManamgoda commented on main.tf
> +}
Let's add a new line

2024-01-04 06:15 UTC, ThilinaManamgoda commented on alerts.tf
> +  source      = "git::https://github.com/wso2/aws-terraform-modules.git//modules/aws/SNS-Topic"
Shall we create a tag from this repo and refer to a particular tag. This is applicable for all the `source` references.

2024-01-04 06:15 UTC, ThilinaManamgoda commented on alerts.tf
> +# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
Let's change the license header year to 2024

2024-01-04 06:15 UTC, ThilinaManamgoda commented on locals.tf
> +}
Let's add a new line

2024-01-04 06:36 UTC, athiththan11 commented on sample_input.tfvars
Shall we keep the sample files in a separate directory and point these sample files in the READ ME to get a copy, rename and fill with required configurations? 

Suggestion: Create a directory named `example` in the root directory of this project and keep the sample configuration file, and  make a note in the READ ME to take a copy and make necessary changes

2024-01-04 06:37 UTC, athiththan11 requested changes
https://github.com/wso2/iac-aws-wso2-products/pull/1/files#r1441388788

2024-01-04 07:01 UTC, athiththan11 commented on README.md
> +This document is autogenerated using terraform-docs (https://github.com/terraform-docs/terraform-docs)
We can remove this portion and add instructions on how to use the modules and what are the prerequisites to be done.

2024-02-08 03:15 UTC, PasanT9 commented on sample_input.tfvars
> +]
Ack. Fixed

2024-02-08 03:15 UTC, PasanT9 commented on main.tf
> +}
Ack. Fixed

2024-02-08 03:15 UTC, PasanT9 commented on alerts.tf
> +  source      = "git::https://github.com/wso2/aws-terraform-modules.git//modules/aws/SNS-Topic"
Ack. Now we are using the tag v1.12.0 which contains latest changes.

2024-02-08 03:15 UTC, PasanT9 commented on alerts.tf
> +# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
Fixed here and other places as well.

2024-02-08 03:16 UTC, PasanT9 commented on locals.tf
> +}
Acl. Fixed.

2024-02-08 03:16 UTC, PasanT9 commented on sample_input.tfvars
Ack. Fixed

2024-02-08 03:16 UTC, PasanT9 commented on README.md
> +This document is autogenerated using terraform-docs (https://github.com/terraform-docs/terraform-docs)
The ReadMe are now upgraded with instructions.

2024-02-26 04:33 UTC, ThilinaManamgoda approved these changes, later dismissed

2024-02-27 03:44 UTC, athiththan11 requested changes

2024-02-27 03:44 UTC, athiththan11 commented on database.tf
> +  backup_retention_period = 7 # TODO parameterize
Why do we need this TODO comments?

2024-02-27 03:44 UTC, athiththan11 commented on locals.tf
> +
Let's remove this extra line

2024-02-27 03:44 UTC, athiththan11 commented on sample/secret.auto.tfvars
Let's add the License Header to this as well

2024-02-27 03:58 UTC, athiththan11 approved these changes

2024-02-27 03:59 UTC, merged